Repository zeplin/vscode-extension, pull requests merged in 2020-04, with the labels that each got.

#10 Fix audit vulnerabilities
  package-lock.json
Labels: bug

#7 Add clear cache option
  package-lock.json
  package.json
  src/coco/barrel/data/BarrelsStoreProvider.ts
  src/coco/barrel/hover/BarrelHoverCreator.ts
  src/coco/config/codeLens/ConfigCodeLensProvider.ts
  src/coco/zeplinComponent/data/BarrelDetailsStoreProvider.ts
  src/coco/zeplinComponent/hover/ZeplinComponentHoverCreator.ts
  src/common/domain/extension/extension.ts
  src/common/domain/hover/zeplinHoverUtil.ts
  src/common/domain/store/BasicStore.ts
  src/common/domain/store/CacheHolder.ts
  src/common/vscode/hover/HoverBuilder.ts
  src/common/vscode/ide/vscodeUtil.ts
  src/localization/localization.ts
  src/session/codeLens/ClearCacheCodeLensCreator.ts
  src/session/command/ClearCacheCommand.ts
  src/session/flow/sessionFlow.ts
Labels: enhancement

#8 Add multiple components command
  package.json
  src/coco/barrel/flow/barrelFlow.ts
  src/coco/component/codeLens/AddMultipleComponentsCodeLensCreator.ts
  src/coco/component/command/AddMultipleComponentsCommand.ts
  src/coco/component/flow/componentFlow.ts
  src/coco/config/codeLens/ConfigCodeLensProvider.ts
  src/coco/zeplinComponent/flow/zeplinComponentFlow.ts
  src/common/domain/extension/extension.ts
  src/common/vscode/quickPick/QuickPickerProvider.ts
  src/localization/localization.ts
Labels: enhancement

#9 Autofill when adding a git repository
  src/coco/config/model/Config.ts
  src/coco/config/util/configUtil.ts
  src/coco/repository/flow/repositoryFlow.ts
  src/coco/repository/util/repositoryUtil.ts
Labels: enhancement

#12 Add connect multiple zeplin components command
  package.json
  src/coco/config/codeLens/ConfigCodeLensProvider.ts
  src/coco/config/util/configUtil.ts
  src/coco/zeplinComponent/codeLens/AddMultipleZeplinComponentsCodeLensCreator.ts
  src/coco/zeplinComponent/command/AddMultipleZeplinComponentsCommand.ts
  src/coco/zeplinComponent/data/ZeplinComponentsStore.ts
  src/coco/zeplinComponent/flow/zeplinComponentFlow.ts
  src/common/domain/extension/extension.ts
  src/localization/localization.ts
Labels: enhancement

#13 Add Zeplin sidebar
  package.json
Labels: enhancement

#14 Auto fill repository fixes
  src/coco/repository/util/repositoryUtil.ts
Labels: bug

#15 Move common add barrel logic
  src/coco/barrel/codeLens/AddBarrelCodeLensCreator.ts
  src/coco/barrel/data/BarrelStore.ts
  src/coco/barrel/data/BarrelsStoreProvider.ts
  src/coco/barrel/data/OrganizationProjectsStore.ts
  src/coco/barrel/data/OrganizationStyleguidesStore.ts
  src/coco/barrel/data/PersonalProjectsStore.ts
  src/coco/barrel/data/PersonalStyleguidesStore.ts
  src/coco/barrel/diagnostic/BarrelDiagnosticCreator.ts
  src/coco/barrel/flow/barrelFlow.ts
  src/coco/barrel/hover/BarrelHoverCreator.ts
  src/coco/barrel/hover/BarrelsPropertyHoverData.ts
  src/coco/barrel/util/barrelUi.ts
  src/coco/barrel/util/barrelUtil.ts
  src/coco/config/model/Config.ts
  src/coco/config/util/configUtil.ts
  src/coco/zeplinComponent/data/BarrelDetailsStore.ts
  src/coco/zeplinComponent/data/BarrelDetailsStoreProvider.ts
  src/coco/zeplinComponent/data/ConfigBarrelsStore.ts
  src/coco/zeplinComponent/data/ProjectDetailsStore.ts
  src/coco/zeplinComponent/data/StyleguideDetailsStore.ts
  src/coco/zeplinComponent/data/ZeplinComponentStore.ts
  src/coco/zeplinComponent/data/ZeplinComponentsStore.ts
  src/coco/zeplinComponent/flow/zeplinComponentFlow.ts
  src/coco/zeplinComponent/model/BarrelDetails.ts
  src/coco/zeplinComponent/model/BarrelError.ts
  src/common/domain/api/api.ts
  src/common/domain/barrel/Barrel.ts
  src/common/domain/barrel/BarrelType.ts
  src/common/domain/barrel/flow/barrelFlow.ts
  src/common/domain/uri/zeplinUrls.ts
  src/localization/localization.ts
Labels: refactor

#17 Move common component classes to common folder
  src/coco/barrel/diagnostic/BarrelDiagnosticCreator.ts
  src/coco/barrel/hover/BarrelHoverCreator.ts
  src/coco/config/util/configUtil.ts
  src/coco/zeplinComponent/data/BarrelDetailsStore.ts
  src/coco/zeplinComponent/data/ConfigBarrelsStore.ts
  src/coco/zeplinComponent/data/ZeplinComponentStore.ts
  src/coco/zeplinComponent/data/ZeplinComponentsStore.ts
  src/coco/zeplinComponent/flow/zeplinComponentFlow.ts
  src/coco/zeplinComponent/model/BarrelDetailsResponse.ts
  src/coco/zeplinComponent/util/zeplinComponentUi.ts
  src/coco/zeplinComponent/util/zeplinComponentUtil.ts
  src/common/domain/barrel/util/barrelUtil.ts
  src/common/domain/error/errorUi.ts
  src/common/domain/zeplinComponent/data/BarrelDetailsStoreProvider.ts
  src/common/domain/zeplinComponent/model/BarrelDetails.ts
  src/common/domain/zeplinComponent/model/BarrelError.ts
  src/common/domain/zeplinComponent/model/ResponseZeplinComponent.ts
  src/common/domain/zeplinComponent/model/ZeplinComponent.ts
  src/common/domain/zeplinComponent/model/ZeplinComponentSection.ts
  src/log/Logger.ts
  src/session/flow/sessionFlow.ts
Labels: refactor

#16 Add barrel to sidebar
  package.json
  src/common/domain/extension/extension.ts
  src/common/vscode/tree/TreeDataProvider.ts
  src/common/vscode/tree/TreeItem.ts
  src/localization/localization.ts
  src/sidebar/barrel/command/AddProjectToSidebarCommand.ts
  src/sidebar/barrel/command/AddStyleguideToSidebarCommand.ts
  src/sidebar/barrel/flow/barrelFlow.ts
  src/sidebar/barrel/tree/BarrelTreeDataProvider.ts
  src/sidebar/barrel/tree/BarrelTreeItem.ts
  src/sidebar/barrel/util/barrelUtil.ts
Labels: enhancement

#19 List components on sidebar
  src/coco/zeplinComponent/data/BarrelDetailsStore.ts
  src/common/domain/zeplinComponent/model/BarrelDetails.ts
  src/common/vscode/tree/ExpandedErrorTreeItem.ts
  src/localization/localization.ts
  src/sidebar/barrel/tree/BarrelTreeItem.ts
  src/sidebar/zeplinComponent/data/CumulativeBarrelDetailsStore.ts
  src/sidebar/zeplinComponent/tree/BarrelZeplinComponentsTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentSectionTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentsTreeItem.ts
  src/sidebar/zeplinComponent/tree/zeplinComponentTreeUtil.ts
Labels: enhancement

#18 Remove barrel from sidebar
  package.json
  src/common/domain/extension/extension.ts
  src/sidebar/barrel/command/RemoveBarrelFromSidebarCommand.ts
  src/sidebar/barrel/tree/BarrelTreeItem.ts
  src/sidebar/barrel/util/barrelUtil.ts
Labels: enhancement

#21 Show barrel thumbnails on sidebar
  src/coco/barrel/data/BarrelStore.ts
  src/sidebar/barrel/tree/BarrelTreeItem.ts
Labels: enhancement

#20 Add open in zeplin to sidebar
  package.json
  src/coco/barrel/hover/BarrelHoverCreator.ts
  src/coco/zeplinComponent/hover/ZeplinComponentHoverCreator.ts
  src/common/domain/error/errorUi.ts
  src/common/domain/extension/extension.ts
  src/common/domain/openInZeplin/model/ApplicationType.ts
  src/common/domain/openInZeplin/util/openInZeplinUtil.ts
  src/common/domain/openInZeplin/util/zeplinUrls.ts
  src/common/domain/tree/TreeItemContext.ts
  src/common/vscode/message/MessageBuilder.ts
  src/common/vscode/tree/ExpandedErrorTreeItem.ts
  src/common/vscode/tree/TreeItem.ts
  src/common/vscode/tree/TreeItemContextProvider.ts
  src/localization/localization.ts
  src/preferences/Preferences.ts
  src/sidebar/barrel/tree/BarrelTreeItem.ts
  src/sidebar/openInZeplin/command/OpenInZeplinCommand.ts
  src/sidebar/openInZeplin/flow/openInZeplinFlow.ts
  src/sidebar/zeplinComponent/tree/BarrelZeplinComponentsTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentSectionTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentsTreeItem.ts
  src/sidebar/zeplinComponent/tree/zeplinComponentTreeUtil.ts
Labels: enhancement

#22 List screens on sidebar
  src/coco/zeplinComponent/data/BarrelDetailsStore.ts
  src/coco/zeplinComponent/model/BarrelDetailsResponse.ts
  src/common/domain/api/api.ts
  src/common/domain/zeplinComponent/model/BarrelDetails.ts
  src/localization/localization.ts
  src/session/flow/sessionFlow.ts
  src/sidebar/barrel/tree/BarrelTreeItem.ts
  src/sidebar/screen/data/ProjectScreensStore.ts
  src/sidebar/screen/data/ScreensStore.ts
  src/sidebar/screen/data/ScreensStoreProvider.ts
  src/sidebar/screen/model/ProjectScreens.ts
  src/sidebar/screen/model/ResponseScreenSection.ts
  src/sidebar/screen/model/Screen.ts
  src/sidebar/screen/model/ScreenSection.ts
  src/sidebar/screen/model/ScreensResponse.ts
  src/sidebar/screen/tree/ScreenSectionTreeItem.ts
  src/sidebar/screen/tree/ScreenTreeItem.ts
  src/sidebar/screen/tree/ScreensTreeItem.ts
Labels: enhancement

#24 Add opening screens and screen sections in zeplin
  src/common/domain/openInZeplin/util/zeplinUrls.ts
  src/common/domain/tree/TreeItemContext.ts
  src/sidebar/openInZeplin/flow/openInZeplinFlow.ts
  src/sidebar/screen/tree/ScreenSectionTreeItem.ts
  src/sidebar/screen/tree/ScreenTreeItem.ts
  src/sidebar/screen/tree/ScreensTreeItem.ts
Labels: enhancement

#25 Refactor for jira links
  src/coco/zeplinComponent/model/BarrelDetailsResponse.ts
  src/coco/zeplinComponent/util/zeplinComponentUtil.ts
  src/common/domain/api/api.ts
  src/common/domain/barrel/data/BarrelDetailsStore.ts
  src/common/domain/barrel/data/BarrelStore.ts
  src/common/domain/barrel/data/BarrelsStoreProvider.ts
  src/common/domain/barrel/data/OrganizationProjectsStore.ts
  src/common/domain/barrel/data/OrganizationStyleguidesStore.ts
  src/common/domain/barrel/data/PersonalProjectsStore.ts
  src/common/domain/barrel/data/PersonalStyleguidesStore.ts
  src/common/domain/barrel/data/ProjectDetailsStore.ts
  src/common/domain/barrel/data/StyleguideDetailsStore.ts
  src/common/domain/barrel/data/WorkspacesStore.ts
  src/common/domain/barrel/flow/barrelFlow.ts
  src/common/domain/barrel/model/BarrelDetailsResponse.ts
  src/common/domain/barrel/model/OrganizationsResponse.ts
  src/common/domain/barrel/model/ProjectDetailsResponse.ts
  src/common/domain/barrel/model/ProjectsResponse.ts
  src/common/domain/barrel/model/ResponseBarrel.ts
  src/common/domain/barrel/model/StyleguideDetailsResponse.ts
  src/common/domain/barrel/model/StyleguidesResponse.ts
  src/common/domain/barrel/model/Workspace.ts
  src/common/domain/screen/model/ResponseScreenSection.ts
  src/common/domain/zeplinComponent/data/BarrelDetailsStoreProvider.ts
  src/common/domain/zeplinComponent/model/BarrelDetails.ts
  src/session/flow/sessionFlow.ts
  src/sidebar/screen/data/ProjectScreensStore.ts
Labels: refactor

#26 Add jira links for screens, sections and projects
  package.json
  src/common/domain/barrel/Barrel.ts
  src/common/domain/barrel/data/BarrelDetailsStore.ts
  src/common/domain/barrel/data/BarrelStore.ts
  src/common/domain/barrel/model/ResponseBarrel.ts
  src/common/domain/extension/extension.ts
  src/common/domain/jira/model/Jira.ts
  src/common/domain/jira/model/JiraAttachable.ts
  src/common/domain/jira/model/JiraType.ts
  src/common/domain/jira/util/jiraUtil.ts
  src/common/domain/store/StaticStore.ts
  src/common/domain/tree/TreeItemContext.ts
  src/localization/localization.ts
  src/sidebar/barrel/tree/BarrelTreeItem.ts
  src/sidebar/jira/command/OpenJiraLinkCommand.ts
  src/sidebar/jira/flow/jiraFlow.ts
  src/sidebar/screen/data/ProjectScreensStore.ts
  src/sidebar/screen/data/ScreensStore.ts
  src/sidebar/screen/model/ResponseScreen.ts
  src/sidebar/screen/model/Screen.ts
  src/sidebar/screen/model/ScreenSection.ts
  src/sidebar/screen/model/ScreensResponse.ts
  src/sidebar/screen/tree/ScreenSectionTreeItem.ts
  src/sidebar/screen/tree/ScreenTreeItem.ts
Labels: enhancement

#27 Fix jira links not shown for screens and sections
  src/sidebar/screen/data/ProjectScreensStore.ts
Labels: bug

#28 Add pinning to sidebar
  package.json
  src/common/domain/extension/extension.ts
  src/common/domain/tree/TreeItemContext.ts
  src/common/vscode/tree/TreeDataProvider.ts
  src/sidebar/barrel/tree/BarrelTreeDataProvider.ts
  src/sidebar/pin/command/PinToSidebarCommand.ts
  src/sidebar/pin/command/UnpinFromSidebarCommand.ts
  src/sidebar/pin/flow/pinFlow.ts
  src/sidebar/pin/model/ComponentPinData.ts
  src/sidebar/pin/model/PinData.ts
  src/sidebar/pin/model/PinType.ts
  src/sidebar/pin/model/ScreenPinData.ts
  src/sidebar/pin/tree/PinTreeDataProvider.ts
  src/sidebar/pin/util/pinUtil.ts
  src/sidebar/screen/tree/ScreenTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentTreeItem.ts
Labels: enhancement

#29 Add unpin all items option to sidebar
  package.json
  src/common/domain/extension/extension.ts
  src/common/vscode/ide/builtinCommands.ts
  src/localization/localization.ts
  src/sidebar/pin/command/UnpinAllFromSidebarCommand.ts
  src/sidebar/pin/flow/pinFlow.ts
  src/sidebar/pin/tree/PinTreeDataProvider.ts
  src/sidebar/pin/util/pinUtil.ts
Labels: enhancement

#30 Fix typos
  src/common/general/imageUtil.ts
  src/common/general/pathUtil.ts
  src/common/general/stringUtil.ts
  src/common/vscode/hover/HoverProvider.ts
  src/common/vscode/quickPick/QuickPickerProvider.ts
Labels: documentation

#31 Add pin screen and component option to pin menu
  package.json
  src/coco/barrel/hover/BarrelHoverCreator.ts
  src/coco/zeplinComponent/flow/zeplinComponentFlow.ts
  src/coco/zeplinComponent/hover/ZeplinComponentHoverCreator.ts
  src/common/domain/barrel/flow/barrelFlow.ts
  src/common/domain/barrel/util/barrelUi.ts
  src/common/domain/extension/extension.ts
  src/common/domain/zeplinComponent/data/ZeplinComponentsStore.ts
  src/common/domain/zeplinComponent/util/zeplinComponentUi.ts
  src/localization/localization.ts
  src/sidebar/pin/command/PinComponentToSidebarCommand.ts
  src/sidebar/pin/command/PinScreenToSidebarCommand.ts
  src/sidebar/pin/data/PinnableComponentsStore.ts
  src/sidebar/pin/data/PinnableScreensStore.ts
  src/sidebar/pin/flow/pinFlow.ts
Labels: enhancement

#32 Add refresh sidebar barrels option
  package.json
  src/common/domain/extension/extension.ts
  src/sidebar/barrel/command/RefreshSidebarBarrelsCommand.ts
  src/sidebar/barrel/flow/barrelFlow.ts
Labels: enhancement

#33 Add empty cases for sidebar
  src/localization/localization.ts
  src/sidebar/barrel/tree/BarrelTreeDataProvider.ts
  src/sidebar/pin/tree/PinTreeDataProvider.ts
  src/sidebar/screen/tree/ScreensTreeItem.ts
Labels: enhancement

#35 Show activity on sidebar
  .eslintrc.js
  src/common/domain/componentLike/model/ComponentLike.ts
  src/common/domain/componentLike/model/User.ts
  src/common/domain/componentLike/model/Version.ts
  src/common/domain/extension/extension.ts
  src/common/domain/image/zeplinImageUtil.ts
  src/common/domain/zeplinComponent/data/ZeplinComponentsStore.ts
  src/common/domain/zeplinComponent/model/ResponseZeplinComponent.ts
  src/common/general/stringUtil.ts
  src/common/vscode/tree/TreeDataProvider.ts
  src/localization/localization.ts
  src/sidebar/activity/data/ActivityStore.ts
  src/sidebar/activity/model/Activity.ts
  src/sidebar/activity/model/DateSlot.ts
  src/sidebar/activity/tree/ActivitySlotTreeItem.ts
  src/sidebar/activity/tree/ActivityTreeDataProvider.ts
  src/sidebar/activity/tree/ActivityTreeItem.ts
  src/sidebar/activity/util/activityUtil.ts
  src/sidebar/barrel/util/barrelUtil.ts
  src/sidebar/pin/data/PinnableComponentsStore.ts
  src/sidebar/screen/data/ProjectScreensStore.ts
  src/sidebar/screen/model/ResponseScreen.ts
  src/sidebar/screen/model/Screen.ts
  src/sidebar/screen/tree/ScreenTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentTreeItem.ts
Labels: enhancement

#36 Apply sidebar refresh to activity
  package.json
  src/common/domain/extension/extension.ts
  src/sidebar/barrel/command/RefreshSidebarBarrelsCommand.ts
  src/sidebar/barrel/flow/barrelFlow.ts
  src/sidebar/refresh/command/RefreshSidebarCommand.ts
  src/sidebar/refresh/util/refreshUtil.ts
Labels: enhancement

#37 Fix activity slot localization
  src/localization/localization.ts
  src/sidebar/activity/tree/ActivitySlotTreeItem.ts
Labels: bug

#34 Reduce package json @types/vscode version
  package.json
Labels: bug
