Repository zeplin/vscode-extension, pull requests merged in 2020-05, with the labels that each got.

#39 Add collapse all options to sidebar
  src/common/vscode/tree/TreeDataProvider.ts
  src/sidebar/activity/tree/ActivityTreeDataProvider.ts
  src/sidebar/barrel/tree/BarrelTreeDataProvider.ts
Labels: enhancement

#38 Add sidebar activity errors and empty state
  .eslintrc.js
  src/common/domain/store/BasicStore.ts
  src/common/vscode/tree/TreeDataProvider.ts
  src/localization/localization.ts
  src/sidebar/activity/tree/ActivityErrorsTreeItem.ts
  src/sidebar/activity/tree/ActivityTreeDataProvider.ts
  src/sidebar/barrel/tree/BarrelTreeDataProvider.ts
  src/sidebar/screen/data/ScreensStore.ts
  src/sidebar/screen/model/ScreensError.ts
Labels: enhancement

#40 Add jump to screen or component feature
  package.json
  src/coco/zeplinComponent/util/zeplinComponentUtil.ts
  src/common/domain/extension/extension.ts
  src/common/domain/zeplinComponent/model/ZeplinComponent.ts
  src/common/vscode/tree/ExpandedErrorTreeItem.ts
  src/common/vscode/tree/TreeDataProvider.ts
  src/common/vscode/tree/TreeItem.ts
  src/localization/localization.ts
  src/sidebar/activity/tree/ActivityErrorsTreeItem.ts
  src/sidebar/activity/tree/ActivitySlotTreeItem.ts
  src/sidebar/activity/tree/ActivityTreeDataProvider.ts
  src/sidebar/activity/tree/ActivityTreeItem.ts
  src/sidebar/barrel/tree/BarrelTreeDataProvider.ts
  src/sidebar/barrel/tree/BarrelTreeItem.ts
  src/sidebar/jumpTo/command/JumpToSidebarItemCommand.ts
  src/sidebar/jumpTo/data/JumpableItemsStore.ts
  src/sidebar/jumpTo/flow/jumpToFlow.ts
  src/sidebar/jumpTo/tree/JumpToTreeItem.ts
  src/sidebar/pin/flow/pinFlow.ts
  src/sidebar/pin/tree/PinTreeDataProvider.ts
  src/sidebar/screen/data/ProjectScreensStore.ts
  src/sidebar/screen/model/Screen.ts
  src/sidebar/screen/tree/ScreenSectionTreeItem.ts
  src/sidebar/screen/tree/ScreenTreeItem.ts
  src/sidebar/screen/tree/ScreensTreeItem.ts
  src/sidebar/screen/util/screenUi.ts
  src/sidebar/zeplinComponent/tree/BarrelZeplinComponentsTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentSectionTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentsTreeItem.ts
  src/sidebar/zeplinComponent/tree/zeplinComponentTreeUtil.ts
Labels: enhancement

#42 Highlight new sidebar items
  src/common/vscode/tree/TreeDataProvider.ts
  src/sidebar/barrel/flow/barrelFlow.ts
  src/sidebar/barrel/tree/BarrelTreeDataProvider.ts
  src/sidebar/pin/flow/pinFlow.ts
  src/sidebar/pin/tree/PinTreeDataProvider.ts
  src/sidebar/pin/util/pinUtil.ts
Labels: enhancement

#41 Fix showing general error on uninvited barrels
  src/common/domain/error/errorUi.ts
Labels: bug

#43 Show unpin inline for pinned items
  package.json
Labels: enhancement

#44 Update sidebar items when data changes
  src/common/domain/store/BasicStore.ts
  src/common/domain/zeplinComponent/data/BarrelDetailsStoreProvider.ts
  src/sidebar/barrel/util/barrelUtil.ts
  src/sidebar/pin/model/ComponentPinData.ts
  src/sidebar/pin/model/PinData.ts
  src/sidebar/pin/model/ScreenPinData.ts
  src/sidebar/pin/tree/PinTreeDataProvider.ts
  src/sidebar/pin/util/pinUtil.ts
  src/sidebar/refresh/util/refreshUtil.ts
  src/sidebar/screen/data/ScreensStoreProvider.ts
Labels: enhancement

#45 Update empty states for sidebar barrels
  package.json
  src/localization/localization.ts
  src/session/Session.ts
  src/sidebar/barrel/tree/BarrelTreeDataProvider.ts
Labels: enhancement

#46 Add open in Zeplin feature to activity
  src/common/domain/tree/TreeItemContext.ts
  src/sidebar/activity/data/ActivityStore.ts
  src/sidebar/activity/model/Activity.ts
  src/sidebar/activity/model/ComponentActivity.ts
  src/sidebar/activity/model/ScreenActivity.ts
  src/sidebar/activity/tree/ActivitySlotTreeItem.ts
  src/sidebar/activity/tree/ActivityTreeDataProvider.ts
  src/sidebar/activity/tree/ActivityTreeItem.ts
  src/sidebar/openInZeplin/flow/openInZeplinFlow.ts
Labels: enhancement

#47 Update activity slots
  src/localization/localization.ts
  src/sidebar/activity/model/Activity.ts
  src/sidebar/activity/model/DateSlot.ts
  src/sidebar/activity/tree/ActivitySlotTreeItem.ts
  src/sidebar/activity/tree/ActivityTreeDataProvider.ts
  src/sidebar/activity/util/activityUi.ts
  src/sidebar/activity/util/activityUtil.ts
Labels: enhancement

#48 Add default sidebar shortcuts
  package.json
Labels: enhancement

#49 Auto refresh sidebar
  src/common/general/dateTimeUtil.ts
  src/sidebar/activity/tree/ActivityTreeDataProvider.ts
  src/sidebar/activity/util/activityUi.ts
  src/sidebar/barrel/tree/BarrelTreeDataProvider.ts
  src/sidebar/refresh/command/RefreshSidebarCommand.ts
  src/sidebar/refresh/util/SidebarRefresher.ts
  src/sidebar/refresh/util/refreshUtil.ts
Labels: enhancement

#50 Fix uri/url wording
  src/coco/barrel/hover/BarrelHoverCreator.ts
  src/coco/zeplinComponent/hover/ZeplinComponentHoverCreator.ts
  src/common/domain/error/errorUi.ts
  src/common/domain/extension/configuration.ts
  src/common/domain/extension/extension.ts
  src/common/domain/hover/zeplinHoverUtil.ts
  src/common/domain/openInZeplin/util/zeplinUris.ts
  src/common/vscode/command/OpenExternalUriCommand.ts
  src/common/vscode/command/OpenExternalUrlCommand.ts
  src/common/vscode/hover/HoverBuilder.ts
  src/common/vscode/hover/hoverUtil.ts
  src/sidebar/activity/model/ComponentActivity.ts
  src/sidebar/activity/model/ScreenActivity.ts
  src/sidebar/openInZeplin/flow/openInZeplinFlow.ts
  webpack.config.js
Labels: bug

#51 Fix unknown user activity preventing activity view
  src/common/domain/componentLike/model/Version.ts
  src/localization/localization.ts
  src/sidebar/activity/model/Activity.ts
  src/sidebar/activity/tree/ActivityTreeItem.ts
Labels: bug

#52 Update sidebar icons
  package.json
  resources/dark/icon-jira.svg
  resources/docs/icon-zeplin.png
  resources/icon-sidebar.svg
  resources/light/icon-jira.svg
  src/sidebar/activity/tree/ActivitySlotTreeItem.ts
  src/sidebar/jumpTo/tree/JumpToTreeItem.ts
  src/sidebar/pin/tree/NoPinnedItemTreeItem.ts
  src/sidebar/pin/tree/PinTreeDataProvider.ts
Labels: enhancement

#53 Open item in zeplin when jump to feature is used
  src/sidebar/activity/model/Activity.ts
  src/sidebar/activity/model/ComponentActivity.ts
  src/sidebar/activity/model/ScreenActivity.ts
  src/sidebar/activity/tree/ActivityTreeItem.ts
  src/sidebar/barrel/tree/BarrelTreeDataProvider.ts
  src/sidebar/barrel/tree/BarrelTreeItem.ts
  src/sidebar/jumpTo/flow/jumpToFlow.ts
  src/sidebar/openInZeplin/flow/openInZeplinFlow.ts
  src/sidebar/openInZeplin/model/ZeplinUriProvider.ts
  src/sidebar/screen/tree/ScreenSectionTreeItem.ts
  src/sidebar/screen/tree/ScreenTreeItem.ts
  src/sidebar/zeplinComponent/tree/BarrelZeplinComponentsTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentSectionTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentTreeItem.ts
Labels: enhancement

#54 Fix screen/component context commands order
  package.json
Labels: bug

#55 Add "Add another barrel" tree item to sidebar
  package.json
  src/common/domain/extension/extension.ts
  src/localization/localization.ts
  src/sidebar/barrel/command/AddBarrelToSidebarCommand.ts
  src/sidebar/barrel/flow/barrelFlow.ts
  src/sidebar/barrel/tree/AddBarrelTreeItem.ts
  src/sidebar/barrel/tree/BarrelTreeDataProvider.ts
Labels: enhancement

#56 Change representation of jump to picker items
  src/common/domain/zeplinComponent/util/zeplinComponentUi.ts
  src/localization/localization.ts
  src/sidebar/jumpTo/flow/jumpToFlow.ts
  src/sidebar/screen/util/screenUi.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentsTreeItem.ts
Labels: enhancement

#57 Show type picker for adding barrel to sidebar
  src/sidebar/barrel/flow/barrelFlow.ts
Labels: enhancement

#58 Remove barrel selection from jump to
  src/coco/zeplinComponent/util/zeplinComponentUtil.ts
  src/common/domain/barrel/data/BarrelDetailsStore.ts
  src/common/domain/zeplinComponent/model/ZeplinComponent.ts
  src/sidebar/jumpTo/data/JumpableItemsStore.ts
  src/sidebar/jumpTo/flow/jumpToFlow.ts
  src/sidebar/screen/data/ProjectScreensStore.ts
  src/sidebar/screen/model/Screen.ts
  src/sidebar/screen/util/screenUi.ts
Labels: enhancement

#59 Fix slowness and data usage of sidebar thumbnails
  src/common/domain/image/zeplinImageUtil.ts
  src/common/vscode/tree/TreeDataProvider.ts
  src/common/vscode/tree/TreeItem.ts
  src/sidebar/activity/tree/ActivityTreeDataProvider.ts
  src/sidebar/barrel/tree/BarrelTreeDataProvider.ts
  src/sidebar/barrel/tree/BarrelTreeItem.ts
  src/sidebar/pin/tree/PinTreeDataProvider.ts
  src/sidebar/refresh/util/SidebarRefresher.ts
  src/sidebar/refresh/util/refreshUtil.ts
  src/sidebar/screen/tree/ScreenTreeItem.ts
  src/sidebar/zeplinComponent/tree/BarrelZeplinComponentsTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentTreeItem.ts
Labels: bug

#60 Update sidebar copies
  package.json
Labels: enhancement

#61 Fix data not being updated when barrel is re-added
  src/common/domain/store/BasicStore.ts
  src/common/domain/zeplinComponent/data/BarrelDetailsStoreProvider.ts
  src/sidebar/barrel/util/barrelUtil.ts
  src/sidebar/screen/data/ScreensStoreProvider.ts
Labels: bug

#62 Update sidebar copies
  package.json
  src/localization/localization.ts
Labels: enhancement

#63 Group sidebar barrels
  src/localization/localization.ts
  src/sidebar/barrel/tree/BarrelTreeDataProvider.ts
Labels: enhancement

#64 Fix audit vulnerabilities
  package-lock.json
  package.json
Labels: bug

#65 Open link of components instead of barrels
  src/common/domain/openInZeplin/util/zeplinUris.ts
  src/sidebar/zeplinComponent/tree/BarrelZeplinComponentsTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentsTreeItem.ts
Labels: enhancement

#66 Remove config creation question
  src/coco/config/flow/configFlow.ts
  src/common/domain/extension/zeplinExtensionUtil.ts
  src/common/vscode/extension/extensionUtil.ts
  src/localization/localization.ts
Labels: enhancement

#68 Add Mixpanel analytics
  package-lock.json
  package.json
  src/analytics/Analytics.ts
  src/analytics/util/MixpanelHelper.ts
  src/analytics/util/analyticsTypeUtil.ts
  src/common/domain/extension/configuration.ts
  src/common/general/booleanUtil.ts
  src/preferences/Preferences.ts
  src/session/flow/sessionFlow.ts
  src/sidebar/activity/model/Activity.ts
  src/sidebar/activity/model/ComponentActivity.ts
  src/sidebar/activity/model/ScreenActivity.ts
  src/sidebar/activity/tree/ActivityTreeItem.ts
  src/sidebar/barrel/flow/barrelFlow.ts
  src/sidebar/barrel/tree/BarrelTreeItem.ts
  src/sidebar/jira/flow/jiraFlow.ts
  src/sidebar/jumpTo/flow/jumpToFlow.ts
  src/sidebar/openInZeplin/flow/openInZeplinFlow.ts
  src/sidebar/openInZeplin/model/ZeplinLinkType.ts
  src/sidebar/openInZeplin/model/ZeplinUriProvider.ts
  src/sidebar/pin/util/pinUtil.ts
  src/sidebar/screen/tree/ScreenSectionTreeItem.ts
  src/sidebar/screen/tree/ScreenTreeItem.ts
  src/sidebar/zeplinComponent/tree/BarrelZeplinComponentsTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentSectionTreeItem.ts
  src/sidebar/zeplinComponent/tree/ZeplinComponentTreeItem.ts
  webpack.config.js
Labels: enhancement

#67 Update readme and description
  README.md
  package.json
  resources/docs/sample.gif
Labels: documentation

#69 Fix empty sidebar barrels view pre vscode v1.44
  src/localization/localization.ts
  src/sidebar/barrel/tree/BarrelTreeDataProvider.ts
Labels: bug

#70 Fix sidebar icons not visible pre vscode v1.41
  package.json
  resources/dark/icon-add.svg
  resources/dark/icon-calendar.svg
  resources/dark/icon-info.svg
  resources/dark/icon-link-external.svg
  resources/dark/icon-pin.svg
  resources/dark/icon-pinned.svg
  resources/dark/icon-search.svg
  resources/light/icon-add.svg
  resources/light/icon-calendar.svg
  resources/light/icon-info.svg
  resources/light/icon-link-external.svg
  resources/light/icon-pin.svg
  resources/light/icon-pinned.svg
  resources/light/icon-search.svg
  src/sidebar/activity/tree/ActivitySlotTreeItem.ts
  src/sidebar/barrel/tree/AddBarrelTreeItem.ts
  src/sidebar/barrel/tree/BarrelTreeDataProvider.ts
  src/sidebar/barrel/tree/NoBarrelTreeItem.ts
  src/sidebar/jumpTo/tree/JumpToTreeItem.ts
  src/sidebar/pin/tree/NoPinnedItemTreeItem.ts
  src/sidebar/pin/tree/PinTreeDataProvider.ts
Labels: bug

#71 Fix mixpanel user id is not correctly logged
  src/analytics/util/MixpanelHelper.ts
Labels: bug

#72 Collect vscode feature versions in one file
  src/common/domain/hover/zeplinHoverUtil.ts
  src/common/vscode/ide/vscodeFeatureVersions.ts
  src/sidebar/barrel/tree/BarrelTreeDataProvider.ts
Labels: refactor

#74 Fix duplicate pins when pin button clicked rapidly
  src/sidebar/pin/util/pinUtil.ts
Labels: bug

#84 Log sidebar events
  src/common/vscode/tree/TreeDataProvider.ts
  src/sidebar/openInZeplin/flow/openInZeplinFlow.ts
Labels: enhancement
